# Generated by Django 2.0.6 on 2018-06-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(db_index=True, max_length=15)),
                ('created_time', models.DateTimeField(db_index=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
