# Generated by Django 2.0.6 on 2018-06-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('created_time', models.DateTimeField()),
                ('message', models.CharField(max_length=240)),
            ],
        ),
    ]
