exclude: migrations
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  sha: v1.3.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
- repo: https://github.com/ambv/black.git
  sha: 18.6b2
  hooks:
  - id: black
    entry: black -l 120 --py36
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    files: \.py$
- repo: https://github.com/prettier/prettier.git
  sha: 1.12.1
  hooks:
  - id: prettier
    files: \.(css|less|scss|ts|tsx|graphql|gql|js|jsx|md)$
