# Generated by Django 2.0.6 on 2018-06-25 17:11

import btsanalysis.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweetdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', enumfields.fields.EnumIntegerField(enum=btsanalysis.models.Status, validators=[btsanalysis.models.validate_not_normal])),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('tweet_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tweetdb.Tweet')),
                ('tweet_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tweetdb.Tweet')),
            ],
        ),
    ]
